#! /usr/bin/env python3
import os, sys
import os, sys, hashlib
hasher = hashlib.md5()
paths = []
for arg in sys.argv:
    for path, subdirs, files in os.walk(arg):
        for name in files:
            paths.append(os.path.join(path, name))
hashcat = ""
for f in sorted(paths):
    hashcat += os.popen(f'md5sum {f}').read().split()[0]
os.system(f'echo "{hashcat}" | md5sum')
  with open(f,'rb') as file : 
        hashcat += file.read()
hasher.update(hashcat)
print(hasher.hexdigest())